I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 225, in script
    scene BG_Forest Day with Dissolve(1)
TypeError: 'Particles' object is not callable

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 225, in script
    scene BG_Forest Day with Dissolve(1)
  File "/home/ivan/Documents/renpy-7.3.5-sdk/renpy/ast.py", line 1389, in execute
    renpy.exports.with_statement(trans, paired)
  File "/home/ivan/Documents/renpy-7.3.5-sdk/renpy/exports.py", line 1601, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "/home/ivan/Documents/renpy-7.3.5-sdk/renpy/display/core.py", line 2251, in do_with
    clear=clear)
  File "/home/ivan/Documents/renpy-7.3.5-sdk/renpy/display/core.py", line 2702, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, **kwargs)
  File "/home/ivan/Documents/renpy-7.3.5-sdk/renpy/display/core.py", line 3047, in interact_core
    new_widget=layers_root)
TypeError: 'Particles' object is not callable

Linux-5.3.0-59-generic-x86_64-with-debian-buster-sid
Ren'Py 7.3.5.606
Isekai: New Horizons 1.0
Sat Jul 25 19:18:22 2020
